### ISSUE TITLE
Can’t find CMakeLists.txt

### ISSUE THREAD

**Issue by nikhola** [etfdevs/ETe#103]
Hi,

Here is what I see when I run cmake (with or without ninja):

CMake Warning:
  Ignoring extra path from command line:

   ".."

CMake Error: The source directory "/somewhere/ETe" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Indeed, this file is not here but I thought that it was built by cmake.

Yours,
Nicolas

**Comment by ensiform** [comment]
What is somewhere/ETe and what did you perform exactly?

**Comment by nikhola** [comment]
On 08/12/2024 22:02:09, Ensiform wrote:

> What is somewhere/ETe and what did you perform exactly?

I git cloned ETe then tried to compile it with that long cmake command line (in a build dir).
Of course, I installed the required dependencies (even ninja).

Yours,
nicolas

**Comment by ensiform** [comment]
Then you didn't CD into the directory with the cmake file first which is in the src directory.
