### ISSUE TITLE
ETRun map causes CL_ParseSnapshot error

### ISSUE THREAD

**Issue by ensiform** [etfdevs/ETe#41]
Map: (Rename to .pk3)
[asdarun1.zip](https://github.com/ensiform/ETe/files/2913280/asdarun1.zip)

`CL_ParseSnapshot: Invalid size 79 for areamask`

The number should always be 32 (sizeof int32_t)

Server is sending this number across which likely means there is a memory corruption somewhere (in server) and the code itself has not changed from vanilla in either client or server.

**Comment by tsiren** [comment]
Checked that sv_snapshot:c func SV_AddEntitiesVisibleFromPoint

	// calculate the visible areas
	frame->areabytes = CM_WriteAreaBits( frame->areabits, clientarea );

indeed calculates 79 bytes

**Comment by ensiform** [comment]
CM_WriteAreaBits unchanged from GPL release ET repo though.

**Comment by tsiren** [comment]
Related variables within that function

origin: 64.000000 272.000000 137.000000
leafnum 24119, clientarea 0, clientcluster 23483

**Comment by tsiren** [comment]
bytes = ( cm.numAreas + 7 ) >> 3;

This shouldn't return more than 32 so something wrong with the numAreas value 630

**Comment by tsiren** [comment]
Based on that max value for numAreas is 256

**Comment by tsiren** [comment]
As mentioned in Discord the official binary differs from the original released sources.

if ( len > sizeof( newSnap.areamask ) ) {
    Com_Error( ERR_DROP,"CL_ParseSnapshot: Invalid size %d for areamask.", len );
    return;
}

This error string is missing from the released binary. You can verify this by running strings <binary> in linux.

**Comment by ensiform** [comment]
And removing it causes other problems still?

**Comment by tsiren** [comment]
It loaded the level but crashes shortly after, I could try some more experimenting

**Comment by ensiform** [comment]
I do not actually have a copy of ET.exe retail release at the moment for some reason so I can't actually confirm if the message is missing from there too. My guess is they added it during the time they added the directory traversal fixes to the code post-release similar to what happened with dirtrav fixes for Q3A, post-Q3 GPL.

**Comment by tsiren** [comment]
I verified that it's also missing from the Windows version.

**Comment by tsiren** [comment]
The level loads fine in ETe if I comment out the size check. You can verify this in your Win build also.

**Comment by ensiform** [comment]
I think suburb told me it should still work without the mod. Need confirmation

**Comment by tsiren** [comment]
I scrolled the discord messages and you should be able to play it without the mod. This means there is more to it than just the error message. It crashes in a way that it totally freezes so I don't get any stack trace. I could try to see where the instruction pointer is but ... maybe trying ETe(remove the error msg) + ETRun gives us better info or the same end result.

**Comment by ensiform** [comment]
Closing but I don't really like that we don't have this check still.
