### ISSUE TITLE
ETRun map "fw" causes client appcrash upon noclip through the ceiling

### ISSUE THREAD

**Issue by suburbski** [etfdevs/ETe#45]
Map: (Rename to .pk3)
[fw.zip](https://github.com/etfdevs/ETe/files/3499906/fw.zip)

Confirmed in ETMain and with ETe latest commit 06b87a1e07d39069494f016d5e6f0dc00f2331a1

According to @isRyven this happens due to a lightgrid parsing issue where the lighting color values  projected onto the player weapon are filled with memory garbage

**Comment by ensiform** [comment]
Cannot reproduce in my local build with debug from going out of map in area where spawning in. Is there specific location to reach first?

**Comment by suburbski** [comment]
Here's a new pk3 of the same map, appcrash didn't happen with the old one

`egyptosoc.shader` file seems to cause problems

 Map: (Rename to .pk3)
[fw.zip](https://github.com/etfdevs/ETe/files/3580144/fw.zip)

**Comment by ensiform** [comment]
Thx. Will check later. My guess is skybox as I use egyptsoc textures extensively in many ETF maps

**Comment by ensiform** [comment]
Still cannot reproduce even with that updated map file :(

**Comment by ensiform** [comment]
What are your settings for:

r_fbo, r_vbo, r_dlightMode, r_hdr, r_bloom

**Comment by suburbski** [comment]
all default `r_fbo = 0;
r_vbo = 0;
r_dlightMode = 1;
r_hdr = 0;
r_bloom = 0`

**Comment by ensiform** [comment]
Try with all on except bloom?

**Comment by suburbski** [comment]
Crashes nevertheless

**Comment by ensiform** [comment]
Okay so it's not those options lol

**Comment by ensiform** [comment]
What about dlightmode 0?

**Comment by suburbski** [comment]
Also crashes with `r_fbo = 0; r_vbo = 0; r_dlightMode = 0; r_hdr = 0; r_bloom = 0`

**Comment by ensiform** [comment]
Then I'm not sure if there's any issue really that can be tracked down to specific feature

**Comment by suburbski** [comment]
Irreproducible
