### ISSUE TITLE
test builds & shadowmaps

### ISSUE THREAD

**Issue by coroner-gss** [etfdevs/ETe#52]
Hi ensiform,

thanks for this great ET engine (and thanks to Q3e).
Just wondering whether you would be motivated to upload a recent win test build. I just tested the last build with TC CQB and I am impressed with the performance. All problems of the original ET with larger maps and many polys on animated models gone.

Are there any plans to get cascaded shadowmaps (e,g. from ioquake 3) in here? A dream for old school renaissance on the ET engine would come true.

Sorry for kinda hijacking the Issues with this.

coroner

**Comment by ensiform** [comment]
renderer2 will never exist. It's bad performance and optimization
