### ISSUE TITLE
Fix win32 build warnings

### ISSUE THREAD

**Issue by tsiren** [etfdevs/ETe#57]
Appveyor warnings should be fixed

**Comment by ensiform** [comment]
Disable any warnings in botlib and splines like was done in CMake for Linux.

Selectively fix or ignore `C4706: assignment within conditional expression`

I can't find many Q3 engine forks that have properly fixed all of the warnings about sign mismatch in tr_ files

**Comment by tsiren** [comment]
Renderer (tr_ files) has no warnings in linux side

**Comment by tsiren** [comment]
If C4706 is not a warning in GCC side as it seems then better just to disable

**Comment by tsiren** [comment]
Or just fix them as there's not many: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4706?view=vs-2019

**Comment by ensiform** [comment]
Fixed in master
