### ISSUE TITLE
Fog cannot be turned off with r_vbo 1

### ISSUE THREAD

**Issue by Aciz** [etfdevs/ETe#75]
`r_wolffog` toggle doesn't work properly when `r_vbo` is enabled, seems like it somehow only partially disables it (see skybox  and the puddle at the road in the images).

`r_vbo 1` `r_wolffog 1`
![2022-09-11-191044-radar](https://user-images.githubusercontent.com/14221121/189537791-8ada790a-5081-4cbf-bc2a-742f971dc596.jpg)

`r_vbo 1` `r_wolffog 0`
![2022-09-11-191048-radar](https://user-images.githubusercontent.com/14221121/189537793-09ca5de5-4743-4074-a3cc-49476a974101.jpg)

`r_vbo 0` `r_wolffog 0`
![2022-09-11-191055-radar](https://user-images.githubusercontent.com/14221121/189537798-0085a189-e7be-4deb-bb16-4be146d79c89.jpg)

**Comment by ensiform** [comment]
Fixed in 413dee18780576ced140f0276e189a32cca5c50b
